name: pipeline pour test A calculator app in Node.js
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Run checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependecies
      run: npm install
      working-directory: ./bootsrap
    
    - name: Lint code
      run: npm run eslint:check

    - name: Run test unitaire
      run: npm run nyc:run
   
    - name: generate coverage report
      run: npm run nyc:coverage
    
    - name: Run functionnal test
      run: npm run cypress:test 
    
    - name: Documentation
      run: npm run jsdoc 